# master-deploy-work.yml

name: master

on:
  push:
    branches: [ main ]  #master브런치에 push가 이뤄질때 작동
  pull_request:
    branches: [ main ]  
  workflow_dispatch:
  
defaults:
  run:
    working-directory: ./ #작업 디렉토르 설정  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --region ap-northeast-2 ./index.html s3://swcamp-html
          aws s3 sync --region ap-northeast-2 ./common s3://swcamp-html
